name: Bump Version

on:
  workflow_call:
    outputs:
      version:
        description: "The new version number"
        value: ${{ jobs.bump.outputs.version }}

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Read and bump version
        id: versioning
        run: |
          VERSION_FILE=Version
          VERSION=$(cat $VERSION_FILE)

          # Split version
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          echo "Old version: $VERSION"
          echo "New version: $NEW_VERSION"

          echo "$NEW_VERSION" > $VERSION_FILE
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit bumped version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Version
          git commit -m "Bump version to ${{ steps.versioning.outputs.version }}"
          git push
