# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Read and bump version
      id: versioning
      run: |
        VERSION_FILE=Version
        VERSION=$(cat $VERSION_FILE)

        # Split version
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"

        echo "Old version: $VERSION"
        echo "New version: $NEW_VERSION"

        echo "$NEW_VERSION" > $VERSION_FILE

        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Commit bumped version
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add VERSION
        git commit -m "Bump version to ${{ steps.versioning.outputs.version }}"
        git push
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
